server {
    listen 80;
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

    # Backend API Route
    location /api/ {
        proxy_pass http://ideapool_api:5139/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Backend Images Route
    location /Images/ {
        proxy_pass http://ideapool_api:5139/Images/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Backend WeatherForecast Route (if used for testing)
    location /weatherforecast {
        proxy_pass http://ideapool_api:5139/weatherforecast;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Frontend Static Files
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
